branches:
  only:
    - despora

language: ruby
rvm:
  - 2.0.0
  - 1.9.3

env:
  - DB=mysql BUILD_TYPE=other
  - DB=mysql BUILD_TYPE=cucumber


bundler_args: "--without development production heroku"
before_script: "./script/ci/before_install.sh"
before_install: "mysql -e 'create database finances;'"
script: "./script/ci/build.sh"

addons:
  firefox: "26.0"
